module.exports = {
  AddReactions: "Adicionar Reações",
  Administrator: "Administrador",
  AttachFiles: "Anexar arquivos",
  BanMembers: "Banir membros",
  ChangeNickname: "Mudar apelido",
  Connect: "Conectar",
  CreateInstantInvite: "Criar convite instantâneo",
  CreatePrivateThreads: "Criar tópicos privados",
  CreatePublicThreads: "Criar tópicos públicos",
  DeafenMembers: "Silenciar membros",
  EmbedLinks: "Incorporar links",
  KickMembers: "Expulsar membros",
  ManageChannels: "Gerenciar canais",
  ManageEmojisAndStickers: "Gerenciar emojis e adesivos",
  ManageEvents: "Gerenciar eventos",
  ManageGuild: "Gerenciar servidor",
  ManageMessages: "Gerenciar mensagens",
  ManageNicknames: "Gerenciar apelidos",
  ManageRoles: "Gerenciar cargos",
  ManageThreads: "Gerenciar tópicos",
  ManageWebhooks: "Gerenciar webhooks",
  MentionEveryone: "Mencionar todos",
  ModerateMembers: "Moderar membros",
  MoveMembers: "Mover membros",
  MuteMembers: "Silenciar membros",
  PrioritySpeaker: "Orador prioritário",
  ReadMessageHistory: "Ler histórico de mensagens",
  RequestToSpeak: "Solicitar para falar",
  SendMessages: "Enviar mensagens",
  SendMessagesInThreads: "Enviar mensagens em tópicos",
  SendTTSMessages: "Enviar mensagens TTS",
  Speak: "Falar",
  Stream: "Transmissão de vídeo",
  UseApplicationCommands: "Usar comandos de aplicativo",
  UseEmbeddedActivities: "Usar atividades incorporadas",
  UseExternalEmojis: "Usar emojis externos",
  UseExternalStickers: "Usar adesivos externos",
  UseVAD: "Usar atividade de voz",
  ViewAuditLog: "Ver log de auditoria",
  ViewChannel: "Ver canal",
  ViewGuildInsights: "Ver insights do servidor",
};
